package com.minhui.vpn.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.minhui.vpn.nat.Conversation;
import com.minhui.vpn.nat.NatSession;
import com.minhui.vpn.video.VideoItem;

import com.minhui.vpn.greenDao.ConversationDao;
import com.minhui.vpn.greenDao.NatSessionDao;
import com.minhui.vpn.greenDao.VideoItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conversationDaoConfig;
    private final DaoConfig natSessionDaoConfig;
    private final DaoConfig videoItemDaoConfig;

    private final ConversationDao conversationDao;
    private final NatSessionDao natSessionDao;
    private final VideoItemDao videoItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        natSessionDaoConfig = daoConfigMap.get(NatSessionDao.class).clone();
        natSessionDaoConfig.initIdentityScope(type);

        videoItemDaoConfig = daoConfigMap.get(VideoItemDao.class).clone();
        videoItemDaoConfig.initIdentityScope(type);

        conversationDao = new ConversationDao(conversationDaoConfig, this);
        natSessionDao = new NatSessionDao(natSessionDaoConfig, this);
        videoItemDao = new VideoItemDao(videoItemDaoConfig, this);

        registerDao(Conversation.class, conversationDao);
        registerDao(NatSession.class, natSessionDao);
        registerDao(VideoItem.class, videoItemDao);
    }
    
    public void clear() {
        conversationDaoConfig.clearIdentityScope();
        natSessionDaoConfig.clearIdentityScope();
        videoItemDaoConfig.clearIdentityScope();
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public NatSessionDao getNatSessionDao() {
        return natSessionDao;
    }

    public VideoItemDao getVideoItemDao() {
        return videoItemDao;
    }

}
